// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TC.Agro.Farm.Infrastructure;

#nullable disable

namespace TC.Agro.Farm.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260207232051_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("WolverineEnabled", "true");

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TC.Agro.Farm.Domain.Aggregates.PlotAggregate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<Guid>("PropertyId")
                        .HasColumnType("uuid")
                        .HasColumnName("property_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_plots");

                    b.HasIndex("PropertyId")
                        .HasDatabaseName("ix_plots_property_id");

                    b.ToTable("plots", "public");
                });

            modelBuilder.Entity("TC.Agro.Farm.Domain.Aggregates.PropertyAggregate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_properties");

                    b.HasIndex("OwnerId")
                        .HasDatabaseName("ix_properties_owner_id");

                    b.ToTable("properties", "public");
                });

            modelBuilder.Entity("TC.Agro.Farm.Domain.Aggregates.SensorAggregate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTimeOffset>("InstalledAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("installed_at");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<Guid>("PlotId")
                        .HasColumnType("uuid")
                        .HasColumnName("plot_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_sensors");

                    b.HasIndex("PlotId")
                        .HasDatabaseName("ix_sensors_plot_id");

                    b.ToTable("sensors", "public");
                });

            modelBuilder.Entity("Wolverine.EntityFrameworkCore.Internals.IncomingMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Attempts")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("attempts");

                    b.Property<byte[]>("Body")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("body");

                    b.Property<DateTimeOffset?>("ExecutionTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("execution_time");

                    b.Property<DateTimeOffset?>("KeepUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("keep_until");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message_type");

                    b.Property<int>("OwnerId")
                        .HasColumnType("integer")
                        .HasColumnName("owner_id");

                    b.Property<string>("ReceivedAt")
                        .HasColumnType("text")
                        .HasColumnName("received_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_wolverine_incoming_envelopes");

                    b.ToTable("wolverine_incoming_envelopes", "wolverine", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("Wolverine.EntityFrameworkCore.Internals.OutgoingMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Attempts")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("attempts");

                    b.Property<byte[]>("Body")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("body");

                    b.Property<DateTimeOffset?>("DeliverBy")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deliver_by");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("destination");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message_type");

                    b.Property<int>("OwnerId")
                        .HasColumnType("integer")
                        .HasColumnName("owner_id");

                    b.HasKey("Id")
                        .HasName("pk_wolverine_outgoing_envelopes");

                    b.ToTable("wolverine_outgoing_envelopes", "wolverine", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("TC.Agro.Farm.Domain.Aggregates.PlotAggregate", b =>
                {
                    b.OwnsOne("TC.Agro.Farm.Domain.ValueObjects.Area", "AreaHectares", b1 =>
                        {
                            b1.Property<Guid>("PlotAggregateId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<double>("Hectares")
                                .HasColumnType("double precision")
                                .HasColumnName("area_hectares");

                            b1.HasKey("PlotAggregateId");

                            b1.ToTable("plots", "public");

                            b1.WithOwner()
                                .HasForeignKey("PlotAggregateId")
                                .HasConstraintName("fk_plots_plots_id");
                        });

                    b.OwnsOne("TC.Agro.Farm.Domain.ValueObjects.Name", "Name", b1 =>
                        {
                            b1.Property<Guid>("PlotAggregateId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("name");

                            b1.HasKey("PlotAggregateId");

                            b1.ToTable("plots", "public");

                            b1.WithOwner()
                                .HasForeignKey("PlotAggregateId")
                                .HasConstraintName("fk_plots_plots_id");
                        });

                    b.OwnsOne("TC.Agro.Farm.Domain.ValueObjects.CropType", "CropType", b1 =>
                        {
                            b1.Property<Guid>("PlotAggregateId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("crop_type");

                            b1.HasKey("PlotAggregateId");

                            b1.ToTable("plots", "public");

                            b1.WithOwner()
                                .HasForeignKey("PlotAggregateId")
                                .HasConstraintName("fk_plots_plots_id");
                        });

                    b.Navigation("AreaHectares")
                        .IsRequired();

                    b.Navigation("CropType")
                        .IsRequired();

                    b.Navigation("Name")
                        .IsRequired();
                });

            modelBuilder.Entity("TC.Agro.Farm.Domain.Aggregates.PropertyAggregate", b =>
                {
                    b.OwnsOne("TC.Agro.Farm.Domain.ValueObjects.Area", "AreaHectares", b1 =>
                        {
                            b1.Property<Guid>("PropertyAggregateId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<double>("Hectares")
                                .HasColumnType("double precision")
                                .HasColumnName("area_hectares");

                            b1.HasKey("PropertyAggregateId");

                            b1.ToTable("properties", "public");

                            b1.WithOwner()
                                .HasForeignKey("PropertyAggregateId")
                                .HasConstraintName("fk_properties_properties_id");
                        });

                    b.OwnsOne("TC.Agro.Farm.Domain.ValueObjects.Name", "Name", b1 =>
                        {
                            b1.Property<Guid>("PropertyAggregateId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("name");

                            b1.HasKey("PropertyAggregateId");

                            b1.ToTable("properties", "public");

                            b1.WithOwner()
                                .HasForeignKey("PropertyAggregateId")
                                .HasConstraintName("fk_properties_properties_id");
                        });

                    b.OwnsOne("TC.Agro.Farm.Domain.ValueObjects.Location", "Location", b1 =>
                        {
                            b1.Property<Guid>("PropertyAggregateId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("Address")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("location_address");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("location_city");

                            b1.Property<string>("Country")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("location_country");

                            b1.Property<double?>("Latitude")
                                .HasColumnType("double precision")
                                .HasColumnName("location_latitude");

                            b1.Property<double?>("Longitude")
                                .HasColumnType("double precision")
                                .HasColumnName("location_longitude");

                            b1.Property<string>("State")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("location_state");

                            b1.HasKey("PropertyAggregateId");

                            b1.ToTable("properties", "public");

                            b1.WithOwner()
                                .HasForeignKey("PropertyAggregateId")
                                .HasConstraintName("fk_properties_properties_id");
                        });

                    b.Navigation("AreaHectares")
                        .IsRequired();

                    b.Navigation("Location")
                        .IsRequired();

                    b.Navigation("Name")
                        .IsRequired();
                });

            modelBuilder.Entity("TC.Agro.Farm.Domain.Aggregates.SensorAggregate", b =>
                {
                    b.OwnsOne("TC.Agro.Farm.Domain.ValueObjects.Name", "Label", b1 =>
                        {
                            b1.Property<Guid>("SensorAggregateId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("Value")
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("label");

                            b1.HasKey("SensorAggregateId");

                            b1.ToTable("sensors", "public");

                            b1.WithOwner()
                                .HasForeignKey("SensorAggregateId")
                                .HasConstraintName("fk_sensors_sensors_id");
                        });

                    b.OwnsOne("TC.Agro.Farm.Domain.ValueObjects.SensorStatus", "Status", b1 =>
                        {
                            b1.Property<Guid>("SensorAggregateId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("status");

                            b1.HasKey("SensorAggregateId");

                            b1.HasIndex("Value")
                                .HasDatabaseName("ix_sensors_status");

                            b1.ToTable("sensors", "public");

                            b1.WithOwner()
                                .HasForeignKey("SensorAggregateId")
                                .HasConstraintName("fk_sensors_sensors_id");
                        });

                    b.OwnsOne("TC.Agro.Farm.Domain.ValueObjects.SensorType", "Type", b1 =>
                        {
                            b1.Property<Guid>("SensorAggregateId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("type");

                            b1.HasKey("SensorAggregateId");

                            b1.HasIndex("Value")
                                .HasDatabaseName("ix_sensors_type");

                            b1.ToTable("sensors", "public");

                            b1.WithOwner()
                                .HasForeignKey("SensorAggregateId")
                                .HasConstraintName("fk_sensors_sensors_id");
                        });

                    b.Navigation("Label");

                    b.Navigation("Status")
                        .IsRequired();

                    b.Navigation("Type")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
