// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TC.Agro.Farm.Infrastructure;

#nullable disable

namespace TC.Agro.Farm.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260311011332_AddSuggestedImageToCropTypes")]
    partial class AddSuggestedImageToCropTypes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("WolverineEnabled", "true");

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TC.Agro.Farm.Domain.Aggregates.CropTypeCatalogAggregate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<bool>("IsSystemDefined")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_system_defined");

                    b.Property<double?>("MaxSoilMoisture")
                        .HasColumnType("double precision")
                        .HasColumnName("max_soil_moisture");

                    b.Property<double?>("MaxTemperature")
                        .HasColumnType("double precision")
                        .HasColumnName("max_temperature");

                    b.Property<double?>("MinHumidity")
                        .HasColumnType("double precision")
                        .HasColumnName("min_humidity");

                    b.Property<double?>("MinSoilMoisture")
                        .HasColumnType("double precision")
                        .HasColumnName("min_soil_moisture");

                    b.Property<double?>("MinTemperature")
                        .HasColumnType("double precision")
                        .HasColumnName("min_temperature");

                    b.Property<string>("RecommendedIrrigationType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("recommended_irrigation_type");

                    b.Property<string>("ScientificName")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("scientific_name");

                    b.Property<string>("SuggestedImage")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("suggested_image");

                    b.Property<int?>("TypicalHarvestCycleMonths")
                        .HasColumnType("integer")
                        .HasColumnName("typical_harvest_cycle_months");

                    b.Property<int?>("TypicalPlantingEndMonth")
                        .HasColumnType("integer")
                        .HasColumnName("typical_planting_end_month");

                    b.Property<int?>("TypicalPlantingStartMonth")
                        .HasColumnType("integer")
                        .HasColumnName("typical_planting_start_month");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_crop_type_catalog");

                    b.ToTable("crop_type_catalog", "public");
                });

            modelBuilder.Entity("TC.Agro.Farm.Domain.Aggregates.CropTypeSuggestionAggregate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<double?>("ConfidenceScore")
                        .HasColumnType("double precision")
                        .HasColumnName("confidence_score");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTimeOffset?>("GeneratedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("generated_at");

                    b.Property<int?>("HarvestCycleMonths")
                        .HasColumnType("integer")
                        .HasColumnName("harvest_cycle_months");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<bool>("IsOverride")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_override");

                    b.Property<bool>("IsStale")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_stale");

                    b.Property<double?>("MaxTemperature")
                        .HasColumnType("double precision")
                        .HasColumnName("max_temperature");

                    b.Property<double?>("MinHumidity")
                        .HasColumnType("double precision")
                        .HasColumnName("min_humidity");

                    b.Property<double?>("MinSoilMoisture")
                        .HasColumnType("double precision")
                        .HasColumnName("min_soil_moisture");

                    b.Property<string>("Model")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("model");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("notes");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<string>("PlantingWindow")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("planting_window");

                    b.Property<Guid>("PropertyId")
                        .HasColumnType("uuid")
                        .HasColumnName("property_id");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("source");

                    b.Property<string>("SuggestedImage")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("suggested_image");

                    b.Property<string>("SuggestedIrrigationType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("suggested_irrigation_type");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_crop_type_suggestions");

                    b.HasIndex("OwnerId")
                        .HasDatabaseName("ix_crop_type_suggestions_owner_id");

                    b.HasIndex("PropertyId")
                        .HasDatabaseName("ix_crop_type_suggestions_property_id");

                    b.HasIndex("PropertyId", "OwnerId")
                        .HasDatabaseName("ix_crop_type_suggestions_property_id_owner_id");

                    b.HasIndex("PropertyId", "Source", "IsActive", "IsStale")
                        .HasDatabaseName("ix_crop_type_suggestions_property_id_source_is_active_is_stale");

                    b.ToTable("crop_type_suggestions", "public");
                });

            modelBuilder.Entity("TC.Agro.Farm.Domain.Aggregates.PlotAggregate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BoundaryGeoJson")
                        .HasColumnType("text")
                        .HasColumnName("boundary_geo_json");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("CropTypeCatalogId")
                        .HasColumnType("uuid")
                        .HasColumnName("crop_type_catalog_id");

                    b.Property<DateTimeOffset>("ExpectedHarvestDate")
                        .HasColumnType("timestamptz")
                        .HasColumnName("expected_harvest_date");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<double?>("Latitude")
                        .HasColumnType("double precision")
                        .HasColumnName("latitude");

                    b.Property<double?>("Longitude")
                        .HasColumnType("double precision")
                        .HasColumnName("longitude");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<DateTimeOffset>("PlantingDate")
                        .HasColumnType("timestamptz")
                        .HasColumnName("planting_date");

                    b.Property<Guid>("PropertyId")
                        .HasColumnType("uuid")
                        .HasColumnName("property_id");

                    b.Property<Guid?>("SelectedCropTypeSuggestionId")
                        .HasColumnType("uuid")
                        .HasColumnName("selected_crop_type_suggestion_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_plots");

                    b.HasIndex("CropTypeCatalogId")
                        .HasDatabaseName("ix_plots_crop_type_catalog_id");

                    b.HasIndex("OwnerId")
                        .HasDatabaseName("ix_plots_owner_id");

                    b.HasIndex("PropertyId")
                        .HasDatabaseName("ix_plots_property_id");

                    b.HasIndex("SelectedCropTypeSuggestionId")
                        .HasDatabaseName("ix_plots_selected_crop_type_suggestion_id");

                    b.ToTable("plots", "public");
                });

            modelBuilder.Entity("TC.Agro.Farm.Domain.Aggregates.PropertyAggregate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_properties");

                    b.HasIndex("OwnerId")
                        .HasDatabaseName("ix_properties_owner_id");

                    b.ToTable("properties", "public");
                });

            modelBuilder.Entity("TC.Agro.Farm.Domain.Aggregates.SensorAggregate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTimeOffset>("InstalledAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("installed_at");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<Guid>("PlotId")
                        .HasColumnType("uuid")
                        .HasColumnName("plot_id");

                    b.Property<string>("StatusChangeReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("status_change_reason");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_sensors");

                    b.HasIndex("OwnerId")
                        .HasDatabaseName("ix_sensors_owner_id");

                    b.HasIndex("PlotId")
                        .HasDatabaseName("ix_sensors_plot_id");

                    b.ToTable("sensors", "public");
                });

            modelBuilder.Entity("TC.Agro.Farm.Domain.Snapshots.OwnerSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("email");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_owner_snapshots");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_owner_snapshots_email");

                    b.ToTable("owner_snapshots", "public");
                });

            modelBuilder.Entity("Wolverine.EntityFrameworkCore.Internals.IncomingMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer")
                        .HasColumnName("attempts");

                    b.Property<byte[]>("Body")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("body");

                    b.Property<DateTimeOffset?>("ExecutionTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("execution_time");

                    b.Property<DateTimeOffset?>("KeepUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("keep_until");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message_type");

                    b.Property<int>("OwnerId")
                        .HasColumnType("integer")
                        .HasColumnName("owner_id");

                    b.Property<string>("ReceivedAt")
                        .HasColumnType("text")
                        .HasColumnName("received_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_wolverine_incoming_envelopes");

                    b.ToTable("wolverine_incoming_envelopes", "wolverine", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("Wolverine.EntityFrameworkCore.Internals.OutgoingMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer")
                        .HasColumnName("attempts");

                    b.Property<byte[]>("Body")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("body");

                    b.Property<DateTimeOffset?>("DeliverBy")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deliver_by");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("destination");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message_type");

                    b.Property<int>("OwnerId")
                        .HasColumnType("integer")
                        .HasColumnName("owner_id");

                    b.HasKey("Id")
                        .HasName("pk_wolverine_outgoing_envelopes");

                    b.ToTable("wolverine_outgoing_envelopes", "wolverine", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("TC.Agro.Farm.Domain.Aggregates.CropTypeCatalogAggregate", b =>
                {
                    b.OwnsOne("TC.Agro.Farm.Domain.ValueObjects.CropType", "CropTypeName", b1 =>
                        {
                            b1.Property<Guid>("CropTypeCatalogAggregateId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("name");

                            b1.HasKey("CropTypeCatalogAggregateId");

                            b1.ToTable("crop_type_catalog", "public");

                            b1.WithOwner()
                                .HasForeignKey("CropTypeCatalogAggregateId")
                                .HasConstraintName("fk_crop_type_catalog_crop_type_catalog_id");
                        });

                    b.Navigation("CropTypeName")
                        .IsRequired();
                });

            modelBuilder.Entity("TC.Agro.Farm.Domain.Aggregates.CropTypeSuggestionAggregate", b =>
                {
                    b.HasOne("TC.Agro.Farm.Domain.Snapshots.OwnerSnapshot", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_crop_type_suggestions_owner_snapshots_owner_id");

                    b.HasOne("TC.Agro.Farm.Domain.Aggregates.PropertyAggregate", "Property")
                        .WithMany()
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_crop_type_suggestions_properties_property_id");

                    b.OwnsOne("TC.Agro.Farm.Domain.ValueObjects.CropType", "CropName", b1 =>
                        {
                            b1.Property<Guid>("CropTypeSuggestionAggregateId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("crop_type");

                            b1.HasKey("CropTypeSuggestionAggregateId");

                            b1.ToTable("crop_type_suggestions", "public");

                            b1.WithOwner()
                                .HasForeignKey("CropTypeSuggestionAggregateId")
                                .HasConstraintName("fk_crop_type_suggestions_crop_type_suggestions_id");
                        });

                    b.Navigation("CropName")
                        .IsRequired();

                    b.Navigation("Owner");

                    b.Navigation("Property");
                });

            modelBuilder.Entity("TC.Agro.Farm.Domain.Aggregates.PlotAggregate", b =>
                {
                    b.HasOne("TC.Agro.Farm.Domain.Aggregates.CropTypeCatalogAggregate", "CropTypeCatalog")
                        .WithMany("Plots")
                        .HasForeignKey("CropTypeCatalogId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_plots_crop_type_catalogs_crop_type_catalog_id");

                    b.HasOne("TC.Agro.Farm.Domain.Snapshots.OwnerSnapshot", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_plots_owner_snapshots_owner_id");

                    b.HasOne("TC.Agro.Farm.Domain.Aggregates.PropertyAggregate", "Property")
                        .WithMany("Plots")
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_plots_properties_property_id");

                    b.HasOne("TC.Agro.Farm.Domain.Aggregates.CropTypeSuggestionAggregate", "SelectedCropTypeSuggestion")
                        .WithMany()
                        .HasForeignKey("SelectedCropTypeSuggestionId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_plots_crop_type_suggestions_selected_crop_type_suggestion_id");

                    b.OwnsOne("TC.Agro.Farm.Domain.ValueObjects.Area", "AreaHectares", b1 =>
                        {
                            b1.Property<Guid>("PlotAggregateId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<double>("Hectares")
                                .HasColumnType("double precision")
                                .HasColumnName("area_hectares");

                            b1.HasKey("PlotAggregateId");

                            b1.ToTable("plots", "public");

                            b1.WithOwner()
                                .HasForeignKey("PlotAggregateId")
                                .HasConstraintName("fk_plots_plots_id");
                        });

                    b.OwnsOne("TC.Agro.Farm.Domain.ValueObjects.Name", "Name", b1 =>
                        {
                            b1.Property<Guid>("PlotAggregateId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("name");

                            b1.HasKey("PlotAggregateId");

                            b1.ToTable("plots", "public");

                            b1.WithOwner()
                                .HasForeignKey("PlotAggregateId")
                                .HasConstraintName("fk_plots_plots_id");
                        });

                    b.OwnsOne("TC.Agro.Farm.Domain.ValueObjects.AdditionalNotes", "AdditionalNotes", b1 =>
                        {
                            b1.Property<Guid>("PlotAggregateId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("Value")
                                .HasMaxLength(1000)
                                .HasColumnType("character varying(1000)")
                                .HasColumnName("additional_notes");

                            b1.HasKey("PlotAggregateId");

                            b1.ToTable("plots", "public");

                            b1.WithOwner()
                                .HasForeignKey("PlotAggregateId")
                                .HasConstraintName("fk_plots_plots_id");
                        });

                    b.OwnsOne("TC.Agro.Farm.Domain.ValueObjects.IrrigationType", "IrrigationType", b1 =>
                        {
                            b1.Property<Guid>("PlotAggregateId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("irrigation_type");

                            b1.HasKey("PlotAggregateId");

                            b1.ToTable("plots", "public");

                            b1.WithOwner()
                                .HasForeignKey("PlotAggregateId")
                                .HasConstraintName("fk_plots_plots_id");
                        });

                    b.Navigation("AdditionalNotes");

                    b.Navigation("AreaHectares")
                        .IsRequired();

                    b.Navigation("CropTypeCatalog");

                    b.Navigation("IrrigationType")
                        .IsRequired();

                    b.Navigation("Name")
                        .IsRequired();

                    b.Navigation("Owner");

                    b.Navigation("Property");

                    b.Navigation("SelectedCropTypeSuggestion");
                });

            modelBuilder.Entity("TC.Agro.Farm.Domain.Aggregates.PropertyAggregate", b =>
                {
                    b.HasOne("TC.Agro.Farm.Domain.Snapshots.OwnerSnapshot", "Owner")
                        .WithMany("Properties")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_properties_owner_snapshots_owner_id");

                    b.OwnsOne("TC.Agro.Farm.Domain.ValueObjects.Area", "AreaHectares", b1 =>
                        {
                            b1.Property<Guid>("PropertyAggregateId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<double>("Hectares")
                                .HasColumnType("double precision")
                                .HasColumnName("area_hectares");

                            b1.HasKey("PropertyAggregateId");

                            b1.ToTable("properties", "public");

                            b1.WithOwner()
                                .HasForeignKey("PropertyAggregateId")
                                .HasConstraintName("fk_properties_properties_id");
                        });

                    b.OwnsOne("TC.Agro.Farm.Domain.ValueObjects.Name", "Name", b1 =>
                        {
                            b1.Property<Guid>("PropertyAggregateId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("name");

                            b1.HasKey("PropertyAggregateId");

                            b1.ToTable("properties", "public");

                            b1.WithOwner()
                                .HasForeignKey("PropertyAggregateId")
                                .HasConstraintName("fk_properties_properties_id");
                        });

                    b.OwnsOne("TC.Agro.Farm.Domain.ValueObjects.Location", "Location", b1 =>
                        {
                            b1.Property<Guid>("PropertyAggregateId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("Address")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("location_address");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("location_city");

                            b1.Property<string>("Country")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("location_country");

                            b1.Property<double?>("Latitude")
                                .HasColumnType("double precision")
                                .HasColumnName("location_latitude");

                            b1.Property<double?>("Longitude")
                                .HasColumnType("double precision")
                                .HasColumnName("location_longitude");

                            b1.Property<string>("State")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("location_state");

                            b1.HasKey("PropertyAggregateId");

                            b1.ToTable("properties", "public");

                            b1.WithOwner()
                                .HasForeignKey("PropertyAggregateId")
                                .HasConstraintName("fk_properties_properties_id");
                        });

                    b.Navigation("AreaHectares")
                        .IsRequired();

                    b.Navigation("Location")
                        .IsRequired();

                    b.Navigation("Name")
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("TC.Agro.Farm.Domain.Aggregates.SensorAggregate", b =>
                {
                    b.HasOne("TC.Agro.Farm.Domain.Snapshots.OwnerSnapshot", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sensors_owner_snapshots_owner_id");

                    b.HasOne("TC.Agro.Farm.Domain.Aggregates.PlotAggregate", "Plot")
                        .WithMany("Sensors")
                        .HasForeignKey("PlotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sensors_plots_plot_id");

                    b.OwnsOne("TC.Agro.Farm.Domain.ValueObjects.Name", "Label", b1 =>
                        {
                            b1.Property<Guid>("SensorAggregateId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("Value")
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("label");

                            b1.HasKey("SensorAggregateId");

                            b1.ToTable("sensors", "public");

                            b1.WithOwner()
                                .HasForeignKey("SensorAggregateId")
                                .HasConstraintName("fk_sensors_sensors_id");
                        });

                    b.OwnsOne("TC.Agro.Farm.Domain.ValueObjects.SensorStatus", "Status", b1 =>
                        {
                            b1.Property<Guid>("SensorAggregateId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("status");

                            b1.HasKey("SensorAggregateId");

                            b1.HasIndex("Value")
                                .HasDatabaseName("ix_sensors_status");

                            b1.ToTable("sensors", "public");

                            b1.WithOwner()
                                .HasForeignKey("SensorAggregateId")
                                .HasConstraintName("fk_sensors_sensors_id");
                        });

                    b.OwnsOne("TC.Agro.Farm.Domain.ValueObjects.SensorType", "Type", b1 =>
                        {
                            b1.Property<Guid>("SensorAggregateId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("type");

                            b1.HasKey("SensorAggregateId");

                            b1.HasIndex("Value")
                                .HasDatabaseName("ix_sensors_type");

                            b1.ToTable("sensors", "public");

                            b1.WithOwner()
                                .HasForeignKey("SensorAggregateId")
                                .HasConstraintName("fk_sensors_sensors_id");
                        });

                    b.Navigation("Label");

                    b.Navigation("Owner");

                    b.Navigation("Plot");

                    b.Navigation("Status")
                        .IsRequired();

                    b.Navigation("Type")
                        .IsRequired();
                });

            modelBuilder.Entity("TC.Agro.Farm.Domain.Aggregates.CropTypeCatalogAggregate", b =>
                {
                    b.Navigation("Plots");
                });

            modelBuilder.Entity("TC.Agro.Farm.Domain.Aggregates.PlotAggregate", b =>
                {
                    b.Navigation("Sensors");
                });

            modelBuilder.Entity("TC.Agro.Farm.Domain.Aggregates.PropertyAggregate", b =>
                {
                    b.Navigation("Plots");
                });

            modelBuilder.Entity("TC.Agro.Farm.Domain.Snapshots.OwnerSnapshot", b =>
                {
                    b.Navigation("Properties");
                });
#pragma warning restore 612, 618
        }
    }
}
